### ISSUE TITLE
是否可以参考CANN的实现来Porting QNN呢？

### ISSUE THREAD

**Issue by bingo787** [chraac/llama.cpp#5]

**Comment by chraac** [comment]
Hi，你好，不好意思才看见你的留言

1. 首先不太明白你这里说的 “参考CANN”，这里是什么意思
2. 如果想说的是可以复用部分代码，那恐怕不行，不同的NPU有不同的结构，然后其对应的软件会有不同的接口，不一定有可复用的部分，如果你有类似的经验，也欢迎提PR修改

**Comment by bingo787** [comment]
CANN是华为Ascend的计算框架。
llama.cpp的仓库里面已经集成了华为的CANN。

**Comment by chraac** [comment]
Hi 你好，如果没有更进一步的comment的话，这个issue我想说是不是可以先关了，如果后面你想贡献代码的话，欢迎提PR
